server:
  port: 8082
spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/catalog}
app:
  internal-key: ${INTERNAL_API_KEY:internal-secret}